# Generated by Django 3.0.6 on 2020-10-19 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_account_client_invalidpostback_client_validpostback_invoice_offerwall_stat_10_stat_24_us_validpostba'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='id',
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.CharField(max_length=300, primary_key=True, serialize=False),
        ),
    ]
