# Generated by Django 3.0.6 on 2020-10-20 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_account_cookie'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='acc_type',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='us_validpostback',
            name='transid',
            field=models.CharField(default='Z', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client_invalidpostback',
            name='reason',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='email',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
