# Generated by Django 3.0.6 on 2020-10-20 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20201020_0451'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='currency',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
