# Generated by Django 3.0.6 on 2020-10-20 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_invoice_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='wall',
            field=models.CharField(default='BBB', max_length=300),
            preserve_default=False,
        ),
    ]
