# Generated by Django 3.0.6 on 2020-10-20 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_offer_wall'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('player', models.CharField(max_length=300)),
                ('linkgate', models.CharField(max_length=300)),
                ('linkway', models.CharField(max_length=300)),
                ('id', models.CharField(max_length=300)),
                ('mainid', models.CharField(max_length=5, primary_key=True, serialize=False)),
            ],
        ),
    ]
