# Generated by Django 3.0.6 on 2020-10-20 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='featured',
            field=models.IntegerField(default=0),
        ),
    ]
