# Generated by Django 3.0.6 on 2020-10-20 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_offer_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
