# Generated by Django 3.0.6 on 2020-10-22 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20201020_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='fullname',
            field=models.CharField(default='MYNAME', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='website',
            field=models.CharField(default='SITE', max_length=300),
            preserve_default=False,
        ),
    ]
