# Generated by Django 3.0.6 on 2020-10-22 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20201022_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='S_Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique', models.CharField(max_length=300)),
                ('method', models.CharField(max_length=300)),
                ('address', models.CharField(blank=True, max_length=300, null=True)),
                ('email', models.CharField(blank=True, max_length=300, null=True)),
                ('international', models.BooleanField(blank=True, null=True)),
                ('firstname', models.CharField(blank=True, max_length=300, null=True)),
                ('lastname', models.CharField(blank=True, max_length=300, null=True)),
                ('stree_addr', models.CharField(blank=True, max_length=300, null=True)),
                ('state', models.CharField(blank=True, max_length=300, null=True)),
                ('city', models.CharField(blank=True, max_length=300, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=300, null=True)),
                ('currency', models.CharField(blank=True, max_length=300, null=True)),
                ('routing', models.CharField(blank=True, max_length=300, null=True)),
                ('acc_number', models.CharField(blank=True, max_length=300, null=True)),
                ('acc_type', models.CharField(blank=True, max_length=300, null=True)),
                ('country', models.CharField(blank=True, max_length=300, null=True)),
                ('biz_type', models.CharField(blank=True, max_length=300, null=True)),
                ('bank_id', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
