# Generated by Django 3.0.6 on 2020-10-22 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_s_invoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='s_invoice',
            old_name='stree_addr',
            new_name='street_addr',
        ),
    ]
