# Generated by Django 3.0.6 on 2020-10-23 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.CharField(max_length=250, primary_key=True, serialize=False),
        ),
    ]
