# Generated by Django 3.0.6 on 2020-10-30 17:49

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20201023_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='Active',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=300)),
                ('wall', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Clicked',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=300)),
                ('status', models.CharField(max_length=300)),
                ('wall', models.IntegerField()),
                ('name', models.CharField(max_length=300)),
                ('offerid', models.CharField(max_length=300)),
                ('earned', models.FloatField()),
                ('data', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='h_balance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='offer',
            name='pic',
            field=models.FileField(blank=True, default='', max_length=500, null=True, storage=django.core.files.storage.FileSystemStorage(location='/var/www/mysite/media/offers/'), upload_to=''),
        ),
    ]
