# Generated by Django 4.1 on 2023-04-18 06:17

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20201030_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featured',
            name='id',
        ),
        migrations.AddField(
            model_name='offer',
            name='orderit',
            field=models.IntegerField(default=main.models.random_string),
        ),
        migrations.AlterField(
            model_name='featured',
            name='unique',
            field=models.CharField(max_length=300, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='offer',
            name='categories',
            field=models.CharField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='offer',
            name='countries',
            field=models.CharField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='offer',
            name='description',
            field=models.CharField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='offer',
            name='requirements',
            field=models.CharField(max_length=3000),
        ),
    ]
